modLoader="javafml"
loaderVersion="[31,)"
license="TODO"

[[mods]]
modId="immersiverailroading"
version="${file.jarVersion}"
displayName="Immersive Railroading"

[[dependencies.immersiverailroading]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverailroading]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.immersiverailroading]]
    modId="universalmodcore"
    mandatory=true
    versionRange="[1.1,1.2)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.trackapi]]
modId="trackapi"
mandatory=true
versionRange="[1.2,)"
ordering="AFTER"
side="BOTH"