name: Immersive Railroading Build Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # branch: [1.7.10-forge, 1.10.2-forge, 1.11.2-forge, 1.12.2-forge, 1.14.4-forge, 1.15.2-forge, 1.16.5-forge]
        branch: [1.12.2-forge]
        include:
#          - branch: 1.7.10-forge
#            umc: latest
#          - branch: 1.10.2-forge
#            umc: latest
#          - branch: 1.11.2-forge
#            umc: latest
#          - branch: 1.10.2-forge
#            umc: latest
          - branch: 1.12.2-forge
            umc: latest
#          - branch: 1.14.4-forge
#            umc: latest
#          - branch: 1.15.2-forge
#            umc: latest
#          - branch: 1.16.5-forge
#            umc: latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: keyscan
      run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
    - name: secrets
      env:
        MAVENCI: ${{ secrets.MAVENCI }}
      run: echo "${MAVENCI}" >> publish_key
    - name: Install deps
      run: sudo apt install -y pngquant findutils xvfb
    - name: Setup Universal Mod Core (and helpers)
      env:
        BRANCH: ${{ matrix.branch }}
        UMC: ${{ matrix.umc }}
      run: .github/workflows/umc.sh integration 1.1.3 ${UMC} && ./gradlew umc -D umc.loader=${BRANCH} -D ssh.http=true
    - name: Hack Forge Gradle
      run: mkdir -p ~/.gradle/caches/minecraft/; wget 'https://teamopenindustry.cc/maven/hack/ForgeGradleVersion.json' -O ~/.gradle/caches/minecraft/ForgeGradleVersion.json
    - name: Gradle compile
      run: ./gradlew classes
    - name: Process images
      run: find src/main/resources/assets/immersiverailroading/ | grep png | xargs -I foo pngquant -s1 -f --ext .png foo
    - name: Run Data (optionalish)
      run: xvfb-run --auto-servernum ./gradlew runData || xvfb-run --auto-servernum ./gradlew runData || true
    - name: Gradle build
      run: ./gradlew build
    - name: Gradle uploadArchives
      run: ./gradlew uploadArchives
    - name: cleanup
      run: rm publish_key
    - uses: actions/upload-artifact@v2
      with:
        name: Immersive Railroading ${{matrix.branch}}
        path: build/libs/ImmersiveRailroading-${{matrix.branch}}-*
